name: release-workflow

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Bump version and publish package(s)

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: 0
      - name: Get tags and filter trigger tags
        run: |
          git fetch --depth=1 origin "+refs/tags/*:refs/tags/*"
          git fetch --prune --unshallow
          git tag -d `git tag | grep -E '^trigger-'`

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache npm
        uses: actions/cache@v1
        id: npm-cache # use this to check for `cache-hit` (`steps.npm-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Run unit tests
        run: npm run test

      - name: Configure npm and git
        run: |
          echo "@superset-ui:registry=https://npm.kysr.me/" > .npmrc
          echo "registry=https://npm.kysr.me/" >> .npmrc
          echo "//npm.kysr.me/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
          npm whoami
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin "https://${GH_TOKEN}@github.com/kyuuseiryuu/superset-ui.git" > /dev/null 2>&1
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Bump version and publish package(s)
        run: |
          git tag -d `git tag | grep -E '^trigger-'`
          npm run ci:release-from-tag
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
